ALTER TABLE issue_events DROP CONSTRAINT issue_events_event_type_check;
ALTER TABLE issue_events ADD CONSTRAINT issue_events_event_type_check CHECK(event_type IN (
 'ISSUE_CREATED','OBSERVATION_ADDED','CLASSIFICATION_UPDATED','STATUS_CHANGED',
 'DIFF_GENERATED','ISSUE_RESOLVED','REVISIT_REVIEWED','ISSUE_UPDATED'));
