import { serve } from '@hono/node-server';
import { Pool } from 'pg';
import { S3Client } from '@aws-sdk/client-s3';
import { resolve } from 'node:path';
import { readConfig } from './config.js';
import { LocalStorageProvider,S3CompatibleStorageProvider } from './storage.js';
import { IntelligenceClient } from './intelligence.js';
import { IssueRepository } from './repository.js';
import { IssueService } from './service.js';
import { createApp } from './app.js';
const config=readConfig();
const pool=new Pool({connectionString:config.DATABASE_URL,max:10,connectionTimeoutMillis:5000,idleTimeoutMillis:30000,statement_timeout:10000,ssl:config.DATABASE_SSL==='true'?{rejectUnauthorized:true}:false});
pool.on('error',()=>console.error('Database pool failure'));
const storage=config.STORAGE_PROVIDER==='local'?new LocalStorageProvider(resolve(config.LOCAL_STORAGE_PATH),config.MEDIA_BASE_URL):new S3CompatibleStorageProvider(new S3Client({endpoint:config.S3_ENDPOINT,region:config.S3_REGION,forcePathStyle:true,credentials:{accessKeyId:config.S3_ACCESS_KEY_ID!,secretAccessKey:config.S3_SECRET_ACCESS_KEY!},maxAttempts:2}),config.S3_BUCKET!,config.MEDIA_BASE_URL);
const intelligence=new IntelligenceClient(config.INTELLIGENCE_URL,config.INTERNAL_SERVICE_TOKEN,config.PROVIDER_TIMEOUT_MS,0);
const repository=new IssueRepository(pool);const service=new IssueService(repository,storage,intelligence);
const app=createApp({service,repository,storage,maxUploadBytes:config.MAX_UPLOAD_BYTES,ready:()=>intelligence.ready()});
const server=serve({fetch:app.fetch,hostname:'0.0.0.0',port:config.PORT},()=>console.log(`FieldIssue API listening on ${config.PORT}`));
let stopping=false;const shutdown=()=>{if(stopping)return;stopping=true;const timeout=setTimeout(()=>process.exit(1),10000);timeout.unref();server.close(()=>{void pool.end().finally(()=>{clearTimeout(timeout);process.exit(0);});});};process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
