// Generated from the public synthetic evaluation by scripts/generate-tinker-examples.mjs.
export const tinkerExamples = {
  recordedAt: "2026-10-09T04:58:03.491641+00:00",
  model: "Qwen/Qwen3-8B",
  modelVersion:
    "tinker://efb40129-33b1-57e0-9f76-6524f961de35:train:0/sampler_weights/fieldissue-note-json-20261009-045450",
  evidenceUrl:
    "https://github.com/himanshu748/fieldissue/blob/main/docs/verification/tinker-evaluation-2026-10-09.json",
  samples: [
    {
      id: "test-cleanliness-01",
      note: "The picnic table has food scraps scattered underneath it.",
      target: {
        category: "CLEANLINESS",
        object: "picnic_table",
        condition: "scraps_scattered_underneath_table",
        severity: "MEDIUM",
        evidence: ["food scraps underneath picnic table"],
      },
      basePrediction: {
        category: "CLEANLINESS",
        object: "picnic_table",
        condition: "food_scattered",
        severity: "LOW",
        evidence: ["food scraps scattered underneath"],
      },
      fineTunedPrediction: {
        category: "CLEANLINESS",
        object: "picnic_table",
        condition: "food_scattered",
        severity: "MEDIUM",
        evidence: ["food scraps under picnic table"],
      },
    },
    {
      id: "test-cleanliness-02",
      note: "Dustbin bhara hai aur kachra bahar gira hai.",
      target: {
        category: "CLEANLINESS",
        object: "waste_bin",
        condition: "full",
        severity: "MEDIUM",
        evidence: ["full dustbin", "garbage fallen outside bin"],
      },
      basePrediction: {
        category: "CLEANLINESS",
        object: "waste_bin",
        condition: "overflowing",
        severity: "HIGH",
        evidence: ["Dustbin bhara hai aur kachra bahar gira hai"],
      },
      fineTunedPrediction: {
        category: "CLEANLINESS",
        object: "waste_bin",
        condition: "overflowing",
        severity: "MEDIUM",
        evidence: ["overflowing waste bin", "spilled garbage"],
      },
    },
    {
      id: "test-infrastructure-01",
      note: "A large hole in the pavement makes most of the lane unusable.",
      target: {
        category: "INFRASTRUCTURE",
        object: "pavement",
        condition: "damaged",
        severity: "HIGH",
        evidence: ["large hole in pavement", "most of lane unusable"],
      },
      basePrediction: {
        category: "INFRASTRUCTURE",
        object: "pavement",
        condition: "large hole",
        severity: "HIGH",
        evidence: [
          "large hole in the pavement",
          "makes most of the lane unusable",
        ],
      },
      fineTunedPrediction: {
        category: "INFRASTRUCTURE",
        object: "pavement",
        condition: "cracked",
        severity: "HIGH",
        evidence: ["large hole in pavement", "lane partially unusable"],
      },
    },
    {
      id: "test-infrastructure-02",
      note: "Drain covr crackd but still in place.",
      target: {
        category: "INFRASTRUCTURE",
        object: "drain_cover",
        condition: "cracked",
        severity: "MEDIUM",
        evidence: ["cracked drain cover", "cover still in place"],
      },
      basePrediction: {
        category: "INFRASTRUCTURE",
        object: "drain_cover",
        condition: "cracked",
        severity: "LOW",
        evidence: ["Drain covr crackd but still in place."],
      },
      fineTunedPrediction: {
        category: "INFRASTRUCTURE",
        object: "drain_cover",
        condition: "cracked",
        severity: "MEDIUM",
        evidence: ["cracked drain cover"],
      },
    },
    {
      id: "test-accessibility-01",
      note: "The accessible entrance is locked and wheelchair users cannot enter.",
      target: {
        category: "ACCESSIBILITY",
        object: "accessible_entrance",
        condition: "locked",
        severity: "HIGH",
        evidence: [
          "accessible entrance locked",
          "wheelchair users cannot enter",
        ],
      },
      basePrediction: {
        category: "ACCESSIBILITY",
        object: "entrance",
        condition: "locked",
        severity: "HIGH",
        evidence: [
          "accessible entrance is locked",
          "wheelchair users cannot enter",
        ],
      },
      fineTunedPrediction: {
        category: "ACCESSIBILITY",
        object: "entrance",
        condition: "locked",
        severity: "HIGH",
        evidence: [
          "locked accessible entrance",
          "wheelchair users unable to enter",
        ],
      },
    },
    {
      id: "test-accessibility-02",
      note: "Curb ramp surface rough.",
      target: {
        category: "ACCESSIBILITY",
        object: "curb_ramp",
        condition: "rough_surface",
        severity: "MEDIUM",
        evidence: ["rough curb ramp surface"],
      },
      basePrediction: {
        category: "ACCESSIBILITY",
        object: "curb_ramp",
        condition: "rough_surface",
        severity: "MEDIUM",
        evidence: ["curb ramp surface rough"],
      },
      fineTunedPrediction: {
        category: "ACCESSIBILITY",
        object: "curb_ramp",
        condition: "rough_surface",
        severity: "MEDIUM",
        evidence: ["rough surface on curb ramp"],
      },
    },
    {
      id: "test-safety-01",
      note: "Exposed live electrical cables are sparking where people are walking now.",
      target: {
        category: "SAFETY",
        object: "electrical_cable",
        condition: "exposed",
        severity: "CRITICAL",
        evidence: ["exposed live cables sparking where people walk now"],
      },
      basePrediction: {
        category: "SAFETY",
        object: "electrical_cable",
        condition: "sparking",
        severity: "CRITICAL",
        evidence: [
          "Exposed live electrical cables are sparking where people are walking now.",
        ],
      },
      fineTunedPrediction: {
        category: "SAFETY",
        object: "electrical_cable",
        condition: "sparking",
        severity: "CRITICAL",
        evidence: ["sparking live cables on walkway"],
      },
    },
    {
      id: "test-safety-02",
      note: "Khula manhole walkway par hai, koi barrier nahi.",
      target: {
        category: "SAFETY",
        object: "manhole",
        condition: "open",
        severity: "HIGH",
        evidence: ["open manhole on walkway", "no barrier"],
      },
      basePrediction: {
        category: "SAFETY",
        object: "manhole",
        condition: "unprotected",
        severity: "HIGH",
        evidence: ["khula manhole walkway par hai", "koi barrier nahi"],
      },
      fineTunedPrediction: {
        category: "SAFETY",
        object: "manhole",
        condition: "uncovered",
        severity: "HIGH",
        evidence: ["uncovered manhole on walkway"],
      },
    },
    {
      id: "test-environment-01",
      note: "An oily patch is visible across the small pond surface.",
      target: {
        category: "ENVIRONMENT",
        object: "pond",
        condition: "oily_film",
        severity: "MEDIUM",
        evidence: ["oily patch on pond surface"],
      },
      basePrediction: {
        category: "ENVIRONMENT",
        object: "pond",
        condition: "oily_patch",
        severity: "MEDIUM",
        evidence: ["oily patch is visible across the small pond surface"],
      },
      fineTunedPrediction: {
        category: "ENVIRONMENT",
        object: "pond",
        condition: "oily_patch",
        severity: "MEDIUM",
        evidence: ["oily patch on pond surface"],
      },
    },
    {
      id: "test-environment-02",
      note: "Tree brnch broke and hangs frm trunk.",
      target: {
        category: "ENVIRONMENT",
        object: "tree_branch",
        condition: "broken",
        severity: "MEDIUM",
        evidence: ["broken tree branch hanging from trunk"],
      },
      basePrediction: {
        category: "SAFETY",
        object: "tree",
        condition: "branch_hanging",
        severity: "HIGH",
        evidence: ["tree brnch broke and hangs frm trunk"],
      },
      fineTunedPrediction: {
        category: "SAFETY",
        object: "tree",
        condition: "branch_hanging",
        severity: "MEDIUM",
        evidence: ["branch hanging from trunk"],
      },
    },
    {
      id: "test-signage-01",
      note: "The exit board is blank; its lettering has worn away.",
      target: {
        category: "SIGNAGE",
        object: "exit_sign",
        condition: "blank",
        severity: "MEDIUM",
        evidence: ["blank exit board", "lettering worn away"],
      },
      basePrediction: {
        category: "SIGNAGE",
        object: "exit_board",
        condition: "unreadable",
        severity: "MEDIUM",
        evidence: ["exit board is blank", "lettering has worn away"],
      },
      fineTunedPrediction: {
        category: "SIGNAGE",
        object: "exit_board",
        condition: "blank",
        severity: "MEDIUM",
        evidence: [
          "exit board has no lettering",
          "lettering on exit board worn away",
        ],
      },
    },
    {
      id: "test-signage-02",
      note: "Trail sign faded.",
      target: {
        category: "SIGNAGE",
        object: "trail_sign",
        condition: "faded",
        severity: "LOW",
        evidence: ["faded trail sign"],
      },
      basePrediction: {
        category: "SIGNAGE",
        object: "trail_sign",
        condition: "faded",
        severity: "LOW",
        evidence: ["trail sign faded"],
      },
      fineTunedPrediction: {
        category: "SIGNAGE",
        object: "trail_sign",
        condition: "faded",
        severity: "MEDIUM",
        evidence: ["faded trail sign"],
      },
    },
    {
      id: "test-lighting-01",
      note: "Three lamps along the path remain dark every evening.",
      target: {
        category: "LIGHTING",
        object: "light",
        condition: "not_working",
        severity: "MEDIUM",
        evidence: ["three path lamps dark every evening"],
      },
      basePrediction: {
        category: "LIGHTING",
        object: "lamp",
        condition: "not functioning",
        severity: "MEDIUM",
        evidence: ["Three lamps along the path remain dark every evening"],
      },
      fineTunedPrediction: {
        category: "LIGHTING",
        object: "lighting",
        condition: "non_functioning",
        severity: "MEDIUM",
        evidence: ["three lamps not working"],
      },
    },
    {
      id: "test-lighting-02",
      note: "Entrance ka lamp raat mein band rehta hai.",
      target: {
        category: "LIGHTING",
        object: "light",
        condition: "not_working",
        severity: "MEDIUM",
        evidence: ["entrance lamp off at night"],
      },
      basePrediction: {
        category: "LIGHTING",
        object: "light",
        condition: "not functioning",
        severity: "MEDIUM",
        evidence: ["Entrance ka lamp raat mein band rehta hai"],
      },
      fineTunedPrediction: {
        category: "LIGHTING",
        object: "light",
        condition: "not working",
        severity: "MEDIUM",
        evidence: ["light not working at entrance"],
      },
    },
    {
      id: "test-trail-01",
      note: "A fallen trunk spans the trail and leaves no room to pass.",
      target: {
        category: "TRAIL",
        object: "trail",
        condition: "blocked",
        severity: "HIGH",
        evidence: ["fallen trunk blocks trail passage"],
      },
      basePrediction: {
        category: "TRAIL",
        object: "trunk",
        condition: "blocking",
        severity: "HIGH",
        evidence: ["A fallen trunk spans the trail and leaves no room to pass"],
      },
      fineTunedPrediction: {
        category: "TRAIL",
        object: "obstruction",
        condition: "blocking",
        severity: "HIGH",
        evidence: ["fallen trunk blocking trail"],
      },
    },
    {
      id: "test-trail-02",
      note: "Hikng tral muddy after heavy rain.",
      target: {
        category: "TRAIL",
        object: "trail",
        condition: "muddy",
        severity: "MEDIUM",
        evidence: ["hiking trail muddy after heavy rain"],
      },
      basePrediction: {
        category: "TRAIL",
        object: "trail",
        condition: "muddy",
        severity: "HIGH",
        evidence: ["Hikng tral muddy after heavy rain."],
      },
      fineTunedPrediction: {
        category: "TRAIL",
        object: "trail",
        condition: "muddy",
        severity: "MEDIUM",
        evidence: ["muddy trail after heavy rain"],
      },
    },
    {
      id: "test-other-01",
      note: "Please inspect this spot; I cannot describe the issue.",
      target: {
        category: "OTHER",
        object: "unknown",
        condition: "unspecified",
        severity: "LOW",
        evidence: [],
      },
      basePrediction: {
        category: "OTHER",
        object: "unknown",
        condition: "unspecified",
        severity: "LOW",
        evidence: [],
      },
      fineTunedPrediction: {
        category: "OTHER",
        object: "unknown",
        condition: "unspecified",
        severity: "LOW",
        evidence: [],
      },
    },
    {
      id: "test-other-02",
      note: "Issue?",
      target: {
        category: "OTHER",
        object: "unknown",
        condition: "unspecified",
        severity: "LOW",
        evidence: [],
      },
      basePrediction: {
        category: "OTHER",
        object: "unknown",
        condition: "unspecified",
        severity: "LOW",
        evidence: [],
      },
      fineTunedPrediction: {
        category: "OTHER",
        object: "unknown",
        condition: "unspecified",
        severity: "LOW",
        evidence: [],
      },
    },
  ],
};
